exports.homeModels =
{
    "HOUSE_MANAGE_NO":"주택관리번호",
    "PBLANC_NO":"공고번호",
    "HOUSE_NM":"주택명",
    "HOUSE_SECD":"주택구분코드",
    "HOUSE_SECD_NM":"주택구분코드명",
    "HOUSE_DTL_SECD":"주택상세구분코드",
    "HOUSE_DTL_SECD_NM":"주택상세구분코드명",
    "RENT_SECD":"분양구분코드",
    "RENT_SECD_NM":"분양구분코드명",
    "SUBSCRPT_AREA_CODE":"공급지역코드",
    "SUBSCRPT_AREA_CODE_NM":"공급지역명",
    "HSSPLY_ZIP":"공급위치 우편번호",
    "HSSPLY_ADRES":"공급위치",
    "TOT_SUPLY_HSHLDCO":"공급규모",
    "RCRIT_PBLANC_DE":"모집공고일 (YYYY-MM-DD)",
    "RCEPT_BGNDE":"청약접수시작일",
    "RCEPT_ENDDE":"청약접수종료일",
    "SPSPLY_RCEPT_BGNDE":"특별공급 접수시작일",
    "SPSPLY_RCEPT_ENDDE":"특별공급 접수종료일",
    "GNRL_RNK1_CRSPAREA_RCEPT_PD":"1순위 접수일 해당지역",
    "GNRL_RNK1_ETC_GG_RCPTDE_PD":"1순위 접수일 경기지역",
    "GNRL_RNK1_ETC_AREA_RCPTDE_PD":"1순위 접수일 기타지역",
    "GNRL_RNK2_CRSPAREA_RCEPT_PD":"2순위 접수일 해당지역",
    "GNRL_RNK2_ETC_GG_RCPTDE_PD":"2순위 접수일 경기지역",
    "GNRL_RNK2_ETC_AREA_RCPTDE_PD":"2순위 접수일 기타지역",
    "PRZWNER_PRESNATN_DE":"당첨자발표일",
    "CNTRCT_CNCLS_BGNDE":"계약시작일",
    "CNTRCT_CNCLS_ENDDE":"계약종료일",
    "HMPG_ADRES":"홈페이지주소",
    "CNSTRCT_ENTRPS_NM":"건설업체명(시공사)",
    "MDHS_TELNO":"문의처",
    "BSNS_MBY_NM":"사업주체명(시행사)",
    "MVN_PREARNGE_YM":"입주예정월",
    "SPECLT_RDN_EARTH_AT":"투기과열지구",
    "MDAT_TRGET_AREA_SECD":"조정대상지역 (Y: 과열지역, D: 위축지역)",
    "PARCPRC_ULS_AT":"분양가상한제",
    "IMPRMN_BSNS_AT":"정비사업",
    "PUBLIC_HOUSE_EARTH_AT":"공공주택지구",
    "LRSCL_BLDLND_AT":"대규모 택지개발지구",
    "NPLN_PRVOPR_PUBLIC_HOUSE_AT":"수도권 내 민영 공공주택지구"
};